<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)../runtimes/win-x64/native/7z.dll"
          Condition="Exists('$(MSBuildThisFileDirectory)../runtimes/win-x64/native/7z.dll')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>runtimes/win-x64/native/7z.dll</TargetPath>
    </None>

    <None Include="$(MSBuildThisFileDirectory)../runtimes/win-arm64/native/7z.dll"
          Condition="Exists('$(MSBuildThisFileDirectory)../runtimes/win-arm64/native/7z.dll')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>runtimes/win-arm64/native/7z.dll</TargetPath>
    </None>

    <None Include="$(MSBuildThisFileDirectory)../runtimes/win-x86/native/7z.dll"
          Condition="Exists('$(MSBuildThisFileDirectory)../runtimes/win-x86/native/7z.dll')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>runtimes/win-x86/native/7z.dll</TargetPath>
    </None>

    <None Include="$(MSBuildThisFileDirectory)../runtimes/osx-arm64/native/7z.dylib"
          Condition="Exists('$(MSBuildThisFileDirectory)../runtimes/osx-arm64/native/7z.dylib')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>runtimes/osx-arm64/native/7z.dylib</TargetPath>
    </None>

    <None Include="$(MSBuildThisFileDirectory)../runtimes/osx-x64/native/7z.dylib"
          Condition="Exists('$(MSBuildThisFileDirectory)../runtimes/osx-x64/native/7z.dylib')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>runtimes/osx-x64/native/7z.dylib</TargetPath>
    </None>

    <None Include="$(MSBuildThisFileDirectory)../runtimes/linux-x64/native/7z.so"
          Condition="Exists('$(MSBuildThisFileDirectory)../runtimes/linux-x64/native/7z.so')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>runtimes/linux-x64/native/7z.so</TargetPath>
    </None>

    <None Include="$(MSBuildThisFileDirectory)../runtimes/linux-arm64/native/7z.so"
          Condition="Exists('$(MSBuildThisFileDirectory)../runtimes/linux-arm64/native/7z.so')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>runtimes/linux-arm64/native/7z.so</TargetPath>
    </None>
  </ItemGroup>

</Project>
