namespace SevenZipSharper.Interop
{
    // Property IDs used by IInArchive.GetProperty (per-entry) and GetArchiveProperty (archive-level).
    // Values match the kpid* constants in the 7-Zip SDK (PropID.h).
    internal enum ItemPropId : uint
    {
        NoProperty = 0,
        MainSubfile = 1,
        HandlerItemIndex = 2,
        Path = 3,
        Name = 4,
        Extension = 5,
        IsDirectory = 6,
        Size = 7,
        PackedSize = 8,
        Attributes = 9,
        CreationTime = 10,
        LastAccessTime = 11,
        LastWriteTime = 12,
        Solid = 13,
        Comment = 14,
        Encrypted = 15,
        SplitBefore = 16,
        SplitAfter = 17,
        DictionarySize = 18,
        Crc = 19,
        Type = 20,
        IsAnti = 21,
        Method = 22,
        HostOs = 23,
        FileSystem = 24,
        User = 25,
        Group = 26,
        Block = 27,
        Position = 29,
        Prefix = 30,
        NumSubDirectories = 31,
        NumSubFiles = 32,
        UnpackVersion = 33,
        Volume = 34,
        IsVolume = 35,
        Offset = 36,
        Links = 37,
        NumBlocks = 38,
        NumVolumes = 39,
        TimeType = 40,
        Bit64 = 41,
        BigEndian = 42,
        Cpu = 43,
        PhysicalSize = 44,
        HeadersSize = 45,
        Checksum = 46,
        PosixAttributes = 53,
        SymLink = 54,
        Error = 55,
        TotalSize = 56,
        FreeSpace = 57,
        ClusterSize = 58,
        VolumeName = 59,
        IsAltStream = 63,
        IsAux = 64,
        IsDeleted = 65,
        NumErrors = 70,
        ErrorFlags = 71,
        WarningFlags = 72,
        Warning = 73,
        NumStreams = 74,
        NumAltStreams = 75,
        AltStreamsSize = 76,
        ReadOnly = 85,
        HardLink = 82,
    }
}
